{"name": "test_abc_002", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <test_001.Test_Abc object at 0x103587c90>\n\n    @allure.severity(allure.severity_level.TRIVIAL)\n    def test_abc_002(self):\n        allure.attach(\"这是第二个一个描述\",\"试一下2\")\n>       assert 0\nE       assert 0\n\nscripts/test_001.py:19: AssertionError"}, "attachments": [{"name": "试一下2", "source": "93705e5b-d129-43c0-b7ec-febcb8f52737-attachment.attach"}], "start": 1588762767691, "stop": 1588762767692, "uuid": "97b992c2-2239-4cb7-9c5d-8f0ee5a2b96c", "historyId": "2d73cbc659e27cd6afec33799f6d4c3a", "testCaseId": "c62d198d12c966461e8ec62ea932140b", "fullName": "scripts.test_001.Test_Abc#test_abc_002", "labels": [{"name": "severity", "value": "trivial"}, {"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_001"}, {"name": "subSuite", "value": "Test_Abc"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "5298-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_001"}]}